import type {
  AccessAssignmentTargetsMetadata,
  RoleDetailRecord,
  RoleTemplateListItem,
  RoleTemplatePreview,
} from '@modules/role/types/role.types';

export const roleDetailFixture: RoleDetailRecord = {
  id: 'role-admin',
  code: 'ADMIN',
  name: 'Admin role',
  description: 'Admin permission template',
  state: 'ACTIVE',
  permissions: [{ code: 'role:view' }, { code: 'user:view' }],
  delegationBand: 'PRIVILEGED',
  maxDelegatableBand: 'LIMITED',
  assignmentRules: [{ id: 'rule-1', code: 'ALLOW_ADMIN', conditions: null }],
  templateCode: 'OWNER_ADMIN',
  templateVersion: '2026-05-20',
  templateAppliedAt: 2,
  createdAt: 1,
  updatedAt: 2,
  activatedAt: 2,
  archivedAt: null,
};

export const lifecycleAssignmentFixture = {
  assignmentId: 'assignment-1',
  targetUserId: 'user-admin',
  roleId: 'role-admin',
  roleCode: 'ADMIN',
  roleName: 'Admin role',
  roleTemplateCode: 'OWNER_ADMIN',
  roleTemplateVersion: '2026-05-20',
  structuredScopeGrants: [{ scopeType: 'self' as const }],
  scopeFingerprint: 'scope:v1:self',
  status: 'ACTIVE' as const,
  lifecycleState: 'ACTIVE' as const,
  currentlyEffective: true,
  inactiveReason: null,
  effectiveAt: 2,
  expiresAt: null,
  reviewAt: null,
  assignedBy: 'user-owner',
  assignedAt: 2,
  revokedAt: null,
  revokedBy: null,
  revokeReason: null,
  origin: 'DIRECT' as const,
  bundleOrigin: null,
  reason: 'Initial assignment',
  sensitiveOrGlobal: false,
  isSensitive: false,
  isGlobalLike: false,
  isHighRisk: false,
  requiresReview: false,
  isBreakGlassLike: false,
  supportedActions: ['REVOKE'],
  auditSummary: {
    assignmentId: 'assignment-1',
    action: 'ASSIGN',
    actorId: 'user-owner',
    timestamp: 2,
    reason: 'Initial assignment',
    oldStatus: null,
    newStatus: 'ACTIVE',
  },
};

export const lifecycleListFixture = {
  readOnly: true,
  sourceTruth: false,
  targetUser: {
    id: 'user-admin',
    displayName: 'Admin User',
    email: 'admin@example.test',
    accountStatus: 'ACTIVE',
  },
  supportedLifecycleActions: ['REVOKE'],
  unsupportedLifecycleActions: ['DISABLE', 'EXPIRE', 'ARCHIVE'],
  items: [lifecycleAssignmentFixture],
  generatedAt: '2026-05-20T00:00:00.000Z',
};

export const lifecycleRevokeFixture = {
  revoked: true,
  lifecycleStatus: 'REVOKED',
  blockers: [],
  warnings: [],
  assignment: {
    ...lifecycleAssignmentFixture,
    status: 'REVOKED' as const,
    lifecycleState: 'REVOKED' as const,
    currentlyEffective: false,
    inactiveReason: 'REVOKED',
    revokedAt: 3,
    revokedBy: 'user-admin',
    revokeReason: 'Done',
    supportedActions: [],
    auditSummary: {
      assignmentId: 'assignment-1',
      action: 'REVOKE',
      actorId: 'user-admin',
      timestamp: 3,
      reason: 'Done',
      oldStatus: 'ACTIVE',
      newStatus: 'REVOKED',
    },
  },
  auditTrace: {
    written: true,
    lifecycleAction: 'REVOKE',
    actorId: 'user-admin',
    assignmentId: 'assignment-1',
    targetUserId: 'user-admin',
    oldStatus: 'ACTIVE',
    newStatus: 'REVOKED',
    reason: 'Done',
    timestamp: 3,
  },
  sourceTrace: {
    mutatesSource: true,
    source: 'role_assignments',
    auditSource: 'audit_log',
  },
  effectiveAccessAfterLifecycle: { permissions: [] },
};

export const roleTemplateCatalogFixture: RoleTemplateListItem[] = [
  {
    code: 'TALENT_GROUP_MANAGER',
    version: '2026-06-26',
    name: 'Talent Group Manager',
    description: 'Team operations preset',
    category: 'MANAGEMENT',
    permissionCount: 15,
    recommendedAccountContext: 'MANAGER_CONSOLE',
    recommendedScopeGrants: {
      workSchedule: ['self', 'team'],
      eventAssignment: ['managedGroup'],
      kpi: ['managedGroup'],
    },
    scopePlan: [
      {
        module: 'Work Schedule',
        scopes: ['self', 'team'],
        status: 'PREVIEW_ONLY',
        note: 'Preview-only scope plan.',
      },
    ],
    warnings: ['Scope plans are preview-only.'],
    implementationNotes: ['Permissions remain explicit.'],
    status: 'PREVIEW_ONLY',
    assignabilityStatus: 'REQUIRES_SCOPE_SELECTION',
    featureStatus: 'SOURCE_BACKED',
    operatorFlowGroup: 'REQUIRES_SCOPE_SELECTION',
    sensitivityLevel: 'STANDARD',
    reviewPolicy: 'NOT_REQUIRED',
    accountContextLifecyclePolicy: 'SYSTEM_DERIVED_PREVIEW_ONLY',
    responsibilityPolicy: 'REQUIRES_EXISTING_RESPONSIBILITY',
    scopeSelectorSupport: 'SUPPORTED',
    futureReadinessNote: null,
    legacyVisibility: 'NORMAL_OPERATOR',
    isSensitive: false,
    isGlobalLike: false,
    isHighRisk: false,
    requiresReview: false,
    isBreakGlassLike: false,
  },
];

export const roleTemplatePreviewFixture: RoleTemplatePreview = {
  template: {
    ...roleTemplateCatalogFixture[0],
    permissions: [{ code: 'workSchedule.read' }, { code: 'talentKpi.read' }],
  },
  permissions: [{ code: 'workSchedule.read' }, { code: 'talentKpi.read' }],
  scopePlan: roleTemplateCatalogFixture[0].scopePlan,
  warnings: roleTemplateCatalogFixture[0].warnings,
  unsupportedScopeNotes: [],
};

export const accessAssignmentTargetsFixture: AccessAssignmentTargetsMetadata = {
  readOnly: false,
  unrestrictedUserListReturned: false,
  searchFirstUserPickerRequired: true,
  eligibleUsersReturned: false,
  userListReturned: false,
  frontendSettableFields: [
    'targetUserId',
    'assignmentTargetType',
    'assignmentTargetCode',
    'bundleVersion',
    'structuredScopeGrants',
    'reason',
  ],
  frontendSettableAuthorityFields: [],
  backendOwnedAuthorityFields: ['accountContext', 'workspaceAvailability', 'actorKind'],
  assignmentTargets: [
    {
      assignmentKind: 'BUNDLE',
      code: 'STAFF_CONSOLE_BUNDLE',
      version: '2026-05-20',
      name: 'Staff Console',
      childRoles: ['STAFF_CONSOLE_USER'],
      recommendedAccountContext: 'STAFF_CONSOLE',
      requiredScopeTypes: ['self'],
      requiresResponsibility: false,
      requiredResponsibilityType: null,
      sensitiveLevel: 'STANDARD',
      legacyAssignable: true,
      assignabilityStatus: 'REQUIRES_SCOPE_SELECTION',
      featureStatus: 'SOURCE_BACKED',
      operatorFlowGroup: 'REQUIRES_SCOPE_SELECTION',
      sensitivityLevel: 'STANDARD',
      reviewPolicy: 'NOT_REQUIRED',
      accountContextLifecyclePolicy: 'SYSTEM_DERIVED_PREVIEW_ONLY',
      responsibilityPolicy: 'NOT_REQUIRED',
      scopeSelectorSupport: 'SUPPORTED',
      futureReadinessNote: null,
      legacyVisibility: 'NORMAL_OPERATOR',
      recommendedPickerMode: 'SEARCH_FIRST',
    },
  ],
  previewRemainsAuthoritative: true,
};
